import Link from "next/link";
import { NewsClient } from "@/components/NewsClient";

export default function NewsPage() {
  return (
    <main className="page-shell">
      <Link href="/" className="eyebrow-link">
        Back to dashboard
      </Link>
      <h1>News Feed</h1>
      <p className="lede">Follow headlines generated by signings, races, and career events.</p>
      <NewsClient />
    </main>
  );
}
